using System.Collections.Generic;

namespace PESolutions.Problems
{
    /// <summary>
    /// Even Fibonacci numbers
    /// <remarks>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
    /// </remarks>
    /// </summary>
    public class Problem2
    {
        public int Solution(int number)
        {
            int[] fib = {1, 2};
            int result = 2;
            int last = 0;
            for (int i = 3; last < number; i++)
            {
                int index = 1 - (i%2);
                last = fib[0] + fib[1];
                fib[index] = last;
                if (last < number && last%2 == 0)
                {
                    result += last;
                }

            }
            return result;
           }
        
    }
}
